export const THEME_DARK = 'THEME_DARK'
export const THEME_LIGHT = 'THEME_LIGHT'
export const SCREEN_TIME = 'SCREEN_TIME'
export const AUTH_USER = 'AUTH_USER'

export const SET_COUNTRY = 'SET_COUNTRY'
export const SET_VALUES = 'SET_VALUES'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const SET_LANG = 'SET_LANG'
export const SET_DEVICE = 'SET_DEVICE'